// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __shmodel__type_hh__
#define __shmodel__type_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_shmodel__type
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_shmodel__type
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_shmodel__type
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





struct shmodel_type {
  typedef _CORBA_ConstrType_Variable_Var<shmodel_type> _var_type;

  
  ::CORBA::Long length;

  ::CORBA::Long width;

  ::CORBA::Long time;

  ::CORBA::Long pop_length;

  ::CORBA::Long pop_width;

  ::CORBA::Long ind_length;

  ::CORBA::Long ind_width;

  typedef _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 >  _s_data_seq;
  _s_data_seq s_data;

  typedef _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 >  _pop_seq;
  _pop_seq pop;

  typedef _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 >  _ind_seq;
  _ind_seq ind;

  typedef _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 >  _nume_seq;
  _nume_seq nume;

  typedef _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 >  _deno_seq;
  _deno_seq deno;



  void operator>>= (cdrStream &) const;
  void operator<<= (cdrStream &);
};

typedef shmodel_type::_var_type shmodel_type_var;

typedef _CORBA_ConstrType_Variable_OUT_arg< shmodel_type,shmodel_type_var > shmodel_type_out;

_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_shmodel_type;









#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const shmodel_type& _s);
extern void operator<<=(::CORBA::Any& _a, shmodel_type* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, shmodel_type*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const shmodel_type*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_shmodel__type
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_shmodel__type
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_shmodel__type
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_shmodel__type
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_shmodel__type
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_shmodel__type
#endif

#endif  // __shmodel__type_hh__

