// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "shmodel_type.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
shmodel_type::operator>>= (cdrStream &_n) const
{
  length >>= _n;
  width >>= _n;
  time >>= _n;
  pop_length >>= _n;
  pop_width >>= _n;
  ind_length >>= _n;
  ind_width >>= _n;
  (const _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &) s_data >>= _n;
  (const _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &) pop >>= _n;
  (const _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &) ind >>= _n;
  (const _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &) nume >>= _n;
  (const _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &) deno >>= _n;

}

void
shmodel_type::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)length <<= _n;
  (::CORBA::Long&)width <<= _n;
  (::CORBA::Long&)time <<= _n;
  (::CORBA::Long&)pop_length <<= _n;
  (::CORBA::Long&)pop_width <<= _n;
  (::CORBA::Long&)ind_length <<= _n;
  (::CORBA::Long&)ind_width <<= _n;
  (_CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &)s_data <<= _n;
  (_CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &)pop <<= _n;
  (_CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &)ind <<= _n;
  (_CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &)nume <<= _n;
  (_CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > &)deno <<= _n;

}

